name: Deploy AWS Step Functions Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04  # Updated to the latest Ubuntu version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Lambda functions
        run: |
          zip fetch_marketing_list.zip fetch_marketing_list.py
          aws lambda create-function --function-name fetch_marketing_list_lambda_handler \
              --runtime python3.9 --handler fetch_marketing_list.lambda_handler \
              --role arn:aws:iam::ACCOUNT_ID:role/LambdaRole \
              --zip-file fileb://fetch_marketing_list.zip

          zip upsert_contacts.zip upsert_contacts_acton.py
          aws lambda create-function --function-name upsert_contacts_lambda_handler \
              --runtime python3.9 --handler upsert_contacts.lambda_handler \
              --role arn:aws:iam::ACCOUNT_ID:role/LambdaRole \
              --zip-file fileb://upsert_contacts.zip

          zip add_to_dss.zip add_to_dss.py
          aws lambda create-function --function-name add_to_dss_lambda_handler \
              --runtime python3.9 --handler add_to_dss.lambda_handler \
              --role arn:aws:iam::ACCOUNT_ID:role/LambdaRole \
              --zip-file fileb://add_to_dss.zip

      - name: Create Step Functions State Machine
        run: |
          aws stepfunctions create-state-machine \
            --name "ActOnIntegrationWorkflow" \
            --definition file://step_functions_workflow.json \
            --role-arn arn:aws:iam::ACCOUNT_ID:role/StepFunctionsRole

      - name: Start Step Functions Execution
        run: |
          aws stepfunctions start-execution \
            --state-machine-arn arn:aws:states:us-east-1:ACCOUNT_ID:stateMachine:ActOnIntegrationWorkflow \
            --input '{"bucket_name": "my-bucket", "file_key": "marketing-list.json", "dss_id": "12345"}'
